name: Update README with Issue List
on:
  issues:
    types:
      - opened
      - edited

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_USEREMAIL: ${{ secrets.GH_USEREMAIL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REPOSITORY: ${{ secrets.REPOSITORY }} # e.g. niwanowa/niwanowa-ideas.git

jobs:
  update_readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github/workflows/update_readme
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README
        run: python update_readme.py

      - name: Set Git Config
        run: |
          git config user.name "${ secrets.GH_USERNAME }"
          git config user.email "${ secrets.GH_USEREMAIL }"

      - name: Commit and Push Changes
        run: |
            git add README.md
            git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${REPOSITORY}
            git commit -m "Update README with latest issues"
            git push